"""Initial migration

Revision ID: d9d0e90c9252
Revises: 
Create Date: 2025-03-03 15:02:23.981910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d0e90c9252'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencers',
    sa.Column('unique_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('im_tracker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('influencer_name', sa.String(length=100), nullable=False),
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.String(length=100), nullable=False),
    sa.Column('activation_for', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('tentative_live_date', sa.Date(), nullable=False),
    sa.Column('landing_page_url', sa.String(length=200), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=False),
    sa.Column('utm_medium', sa.String(length=100), nullable=False),
    sa.Column('utm_campaign', sa.String(length=100), nullable=False),
    sa.Column('utm_string', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['unique_id'], ['influencers.unique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('im_tracker')
    op.drop_table('influencers')
    # ### end Alembic commands ###
